# Generated by Django 6.0.5 on 2026-05-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('kickoff', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='scheduled', max_length=15)),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('api_match_id', models.CharField(max_length=100)),
            ],
        ),
    ]
