# Generated by Django 6.0.5 on 2026-05-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('TIMED', 'TIMED'), ('IN_PLAY', 'IN_PLAY'), ('FINISHED', 'FINISHED')], default='scheduled', max_length=15),
        ),
    ]
