# Generated by Django 6.0.5 on 2026-05-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('matches', '0002_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='matches',
            field=models.ManyToManyField(blank=True, to='matches.match'),
        ),
    ]
